import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  storyWrapper: {
    alignItems: "center",
    marginRight: 14,
  },
  avatarWrapper: {
    position: "relative",
  },
  storyAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    // borderWidth: 2,
    // borderColor: "#f28a2e",
  },
  addIcon: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#fff",
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#000",
  },
  storyLabel: {
    marginTop: 6,
    fontSize: 12,
    color: "#333232",
    fontWeight: "500",
  },
  postContainer: {
    backgroundColor: "#c7ccb4",
    borderWidth: 1,
    borderColor: "#333232",
    borderRadius: 20,
    padding: 12,
    marginVertical: 10,
    marginHorizontal: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  postHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  postAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: 8,
  },
  userName: { fontWeight: "bold", fontSize: 15, color: "#222" },
  postTitle: {
    fontSize: 25,
    fontWeight: "600",
    marginVertical: 8,
    color: "#333232",
  },
  media: {
    width: 391,
    height: 240,
    marginRight: 10,
    borderRadius: 14,
  },
  actions: {
    flexDirection: "row",
    marginTop: 8,
    marginBottom: 6,
  },
  actionText: {
    marginRight: 20,
    fontWeight: "600",
    fontSize: 14,
    color: "#444",
  },
  commentRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
    paddingVertical: 4,
  },
  commentAvatar: {
    width: 22,
    height: 22,
    borderRadius: 11,
    marginRight: 6,
  },
  commentName: { fontWeight: "600", marginRight: 6, fontSize: 13 },
  comment: {
    backgroundColor: "#eee",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    fontSize: 13,
    color: "#333",
  },
  commentInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: "#eee",
    paddingTop: 6,
  },
  commentInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 20,
    paddingHorizontal: 14,
    height: 36,
    backgroundColor: "#fafafa",
    fontSize: 13,
  },
  newPostContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    backgroundColor: "#F5EFE1",
    borderTopWidth: 1,
    borderTopColor: "#ddd",
  },
  newPostInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 20,
    paddingHorizontal: 14,
    height: 38,
    backgroundColor: "#fafafa",
    fontSize: 14,
    marginBottom: 30,
  },
  mediaButton: {
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "#eee",
    marginBottom: 30,
  },
  newPostButton: {
    marginLeft: 8,
    backgroundColor: "#5C00DF",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 30,
  },
  icon: {
    marginLeft: 20,
  },
  mediaPreviewWrapper: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginVertical: 8,
  },
  mediaPreviewItem: {
    width: 70,
    height: 70,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ddd",
    margin: 4,
    overflow: "hidden",
    position: "relative",
  },
  mediaDeleteButton: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 12,
    width: 28,
    height: 28,
    justifyContent: "center",
    alignItems: "center",
  },
});